# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: deflateinfo.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='deflateinfo.proto',
  package='DEFLATEProto',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x11\x64\x65\x66lateinfo.proto\x12\x0c\x44\x45\x46LATEProto\"\x18\n\x07Literal\x12\r\n\x05value\x18\x01 \x01(\r\"+\n\x07\x42\x61\x63kref\x12\x0e\n\x06length\x18\x01 \x01(\r\x12\x10\n\x08\x64istance\x18\x02 \x01(\r\"A\n\rOffsetBackref\x12\x0e\n\x06offset\x18\x01 \x01(\r\x12\x0e\n\x06length\x18\x02 \x01(\r\x12\x10\n\x08\x64istance\x18\x03 \x01(\r\"\x92\x01\n\nDeflateSym\x12$\n\x03lit\x18\x01 \x01(\x0b\x32\x15.DEFLATEProto.LiteralH\x00\x12(\n\x07\x62\x61\x63kref\x18\x02 \x01(\x0b\x32\x15.DEFLATEProto.BackrefH\x00\x12-\n\x06offset\x18\x03 \x01(\x0b\x32\x1b.DEFLATEProto.OffsetBackrefH\x00\x42\x05\n\x03sym\"!\n\x11UncompressedBlock\x12\x0c\n\x04\x64\x61ta\x18\x01 \x01(\x0c\"\xb3\x02\n\x0f\x43ompressedBlock\x12H\n\x0elenlit_codelen\x18\x03 \x03(\x0b\x32\x30.DEFLATEProto.CompressedBlock.LenlitCodelenEntry\x12\x44\n\x0c\x64ist_codelen\x18\x04 \x03(\x0b\x32..DEFLATEProto.CompressedBlock.DistCodelenEntry\x12&\n\x04\x64\x61ta\x18\x01 \x03(\x0b\x32\x18.DEFLATEProto.DeflateSym\x1a\x34\n\x12LenlitCodelenEntry\x12\x0b\n\x03key\x18\x01 \x01(\r\x12\r\n\x05value\x18\x02 \x01(\r:\x02\x38\x01\x1a\x32\n\x10\x44istCodelenEntry\x12\x0b\n\x03key\x18\x01 \x01(\r\x12\r\n\x05value\x18\x02 \x01(\r:\x02\x38\x01\"y\n\x0fUnderlyingBlock\x12.\n\x03raw\x18\n \x01(\x0b\x32\x1f.DEFLATEProto.UncompressedBlockH\x00\x12.\n\x05\x62lock\x18\x01 \x01(\x0b\x32\x1d.DEFLATEProto.CompressedBlockH\x00\x42\x06\n\x04\x64\x61ta\"K\n\x0c\x44\x45\x46LATEBlock\x12\x0e\n\x06\x62\x66inal\x18\x01 \x01(\x08\x12+\n\x04\x64\x61ta\x18\x02 \x01(\x0b\x32\x1d.DEFLATEProto.UnderlyingBlock\";\n\rDEFLATEStream\x12*\n\x06\x62locks\x18\x01 \x03(\x0b\x32\x1a.DEFLATEProto.DEFLATEBlockb\x06proto3'
)




_LITERAL = _descriptor.Descriptor(
  name='Literal',
  full_name='DEFLATEProto.Literal',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='value', full_name='DEFLATEProto.Literal.value', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=35,
  serialized_end=59,
)


_BACKREF = _descriptor.Descriptor(
  name='Backref',
  full_name='DEFLATEProto.Backref',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='length', full_name='DEFLATEProto.Backref.length', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='distance', full_name='DEFLATEProto.Backref.distance', index=1,
      number=2, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=61,
  serialized_end=104,
)


_OFFSETBACKREF = _descriptor.Descriptor(
  name='OffsetBackref',
  full_name='DEFLATEProto.OffsetBackref',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='offset', full_name='DEFLATEProto.OffsetBackref.offset', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='length', full_name='DEFLATEProto.OffsetBackref.length', index=1,
      number=2, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='distance', full_name='DEFLATEProto.OffsetBackref.distance', index=2,
      number=3, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=106,
  serialized_end=171,
)


_DEFLATESYM = _descriptor.Descriptor(
  name='DeflateSym',
  full_name='DEFLATEProto.DeflateSym',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='lit', full_name='DEFLATEProto.DeflateSym.lit', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='backref', full_name='DEFLATEProto.DeflateSym.backref', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='offset', full_name='DEFLATEProto.DeflateSym.offset', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='sym', full_name='DEFLATEProto.DeflateSym.sym',
      index=0, containing_type=None,
      create_key=_descriptor._internal_create_key,
    fields=[]),
  ],
  serialized_start=174,
  serialized_end=320,
)


_UNCOMPRESSEDBLOCK = _descriptor.Descriptor(
  name='UncompressedBlock',
  full_name='DEFLATEProto.UncompressedBlock',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='data', full_name='DEFLATEProto.UncompressedBlock.data', index=0,
      number=1, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=322,
  serialized_end=355,
)


_COMPRESSEDBLOCK_LENLITCODELENENTRY = _descriptor.Descriptor(
  name='LenlitCodelenEntry',
  full_name='DEFLATEProto.CompressedBlock.LenlitCodelenEntry',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='key', full_name='DEFLATEProto.CompressedBlock.LenlitCodelenEntry.key', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='value', full_name='DEFLATEProto.CompressedBlock.LenlitCodelenEntry.value', index=1,
      number=2, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=b'8\001',
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=561,
  serialized_end=613,
)

_COMPRESSEDBLOCK_DISTCODELENENTRY = _descriptor.Descriptor(
  name='DistCodelenEntry',
  full_name='DEFLATEProto.CompressedBlock.DistCodelenEntry',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='key', full_name='DEFLATEProto.CompressedBlock.DistCodelenEntry.key', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='value', full_name='DEFLATEProto.CompressedBlock.DistCodelenEntry.value', index=1,
      number=2, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=b'8\001',
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=615,
  serialized_end=665,
)

_COMPRESSEDBLOCK = _descriptor.Descriptor(
  name='CompressedBlock',
  full_name='DEFLATEProto.CompressedBlock',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='lenlit_codelen', full_name='DEFLATEProto.CompressedBlock.lenlit_codelen', index=0,
      number=3, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='dist_codelen', full_name='DEFLATEProto.CompressedBlock.dist_codelen', index=1,
      number=4, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='data', full_name='DEFLATEProto.CompressedBlock.data', index=2,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[_COMPRESSEDBLOCK_LENLITCODELENENTRY, _COMPRESSEDBLOCK_DISTCODELENENTRY, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=358,
  serialized_end=665,
)


_UNDERLYINGBLOCK = _descriptor.Descriptor(
  name='UnderlyingBlock',
  full_name='DEFLATEProto.UnderlyingBlock',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='raw', full_name='DEFLATEProto.UnderlyingBlock.raw', index=0,
      number=10, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='block', full_name='DEFLATEProto.UnderlyingBlock.block', index=1,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='data', full_name='DEFLATEProto.UnderlyingBlock.data',
      index=0, containing_type=None,
      create_key=_descriptor._internal_create_key,
    fields=[]),
  ],
  serialized_start=667,
  serialized_end=788,
)


_DEFLATEBLOCK = _descriptor.Descriptor(
  name='DEFLATEBlock',
  full_name='DEFLATEProto.DEFLATEBlock',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='bfinal', full_name='DEFLATEProto.DEFLATEBlock.bfinal', index=0,
      number=1, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='data', full_name='DEFLATEProto.DEFLATEBlock.data', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=790,
  serialized_end=865,
)


_DEFLATESTREAM = _descriptor.Descriptor(
  name='DEFLATEStream',
  full_name='DEFLATEProto.DEFLATEStream',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='blocks', full_name='DEFLATEProto.DEFLATEStream.blocks', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=867,
  serialized_end=926,
)

_DEFLATESYM.fields_by_name['lit'].message_type = _LITERAL
_DEFLATESYM.fields_by_name['backref'].message_type = _BACKREF
_DEFLATESYM.fields_by_name['offset'].message_type = _OFFSETBACKREF
_DEFLATESYM.oneofs_by_name['sym'].fields.append(
  _DEFLATESYM.fields_by_name['lit'])
_DEFLATESYM.fields_by_name['lit'].containing_oneof = _DEFLATESYM.oneofs_by_name['sym']
_DEFLATESYM.oneofs_by_name['sym'].fields.append(
  _DEFLATESYM.fields_by_name['backref'])
_DEFLATESYM.fields_by_name['backref'].containing_oneof = _DEFLATESYM.oneofs_by_name['sym']
_DEFLATESYM.oneofs_by_name['sym'].fields.append(
  _DEFLATESYM.fields_by_name['offset'])
_DEFLATESYM.fields_by_name['offset'].containing_oneof = _DEFLATESYM.oneofs_by_name['sym']
_COMPRESSEDBLOCK_LENLITCODELENENTRY.containing_type = _COMPRESSEDBLOCK
_COMPRESSEDBLOCK_DISTCODELENENTRY.containing_type = _COMPRESSEDBLOCK
_COMPRESSEDBLOCK.fields_by_name['lenlit_codelen'].message_type = _COMPRESSEDBLOCK_LENLITCODELENENTRY
_COMPRESSEDBLOCK.fields_by_name['dist_codelen'].message_type = _COMPRESSEDBLOCK_DISTCODELENENTRY
_COMPRESSEDBLOCK.fields_by_name['data'].message_type = _DEFLATESYM
_UNDERLYINGBLOCK.fields_by_name['raw'].message_type = _UNCOMPRESSEDBLOCK
_UNDERLYINGBLOCK.fields_by_name['block'].message_type = _COMPRESSEDBLOCK
_UNDERLYINGBLOCK.oneofs_by_name['data'].fields.append(
  _UNDERLYINGBLOCK.fields_by_name['raw'])
_UNDERLYINGBLOCK.fields_by_name['raw'].containing_oneof = _UNDERLYINGBLOCK.oneofs_by_name['data']
_UNDERLYINGBLOCK.oneofs_by_name['data'].fields.append(
  _UNDERLYINGBLOCK.fields_by_name['block'])
_UNDERLYINGBLOCK.fields_by_name['block'].containing_oneof = _UNDERLYINGBLOCK.oneofs_by_name['data']
_DEFLATEBLOCK.fields_by_name['data'].message_type = _UNDERLYINGBLOCK
_DEFLATESTREAM.fields_by_name['blocks'].message_type = _DEFLATEBLOCK
DESCRIPTOR.message_types_by_name['Literal'] = _LITERAL
DESCRIPTOR.message_types_by_name['Backref'] = _BACKREF
DESCRIPTOR.message_types_by_name['OffsetBackref'] = _OFFSETBACKREF
DESCRIPTOR.message_types_by_name['DeflateSym'] = _DEFLATESYM
DESCRIPTOR.message_types_by_name['UncompressedBlock'] = _UNCOMPRESSEDBLOCK
DESCRIPTOR.message_types_by_name['CompressedBlock'] = _COMPRESSEDBLOCK
DESCRIPTOR.message_types_by_name['UnderlyingBlock'] = _UNDERLYINGBLOCK
DESCRIPTOR.message_types_by_name['DEFLATEBlock'] = _DEFLATEBLOCK
DESCRIPTOR.message_types_by_name['DEFLATEStream'] = _DEFLATESTREAM
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Literal = _reflection.GeneratedProtocolMessageType('Literal', (_message.Message,), {
  'DESCRIPTOR' : _LITERAL,
  '__module__' : 'deflateinfo_pb2'
  # @@protoc_insertion_point(class_scope:DEFLATEProto.Literal)
  })
_sym_db.RegisterMessage(Literal)

Backref = _reflection.GeneratedProtocolMessageType('Backref', (_message.Message,), {
  'DESCRIPTOR' : _BACKREF,
  '__module__' : 'deflateinfo_pb2'
  # @@protoc_insertion_point(class_scope:DEFLATEProto.Backref)
  })
_sym_db.RegisterMessage(Backref)

OffsetBackref = _reflection.GeneratedProtocolMessageType('OffsetBackref', (_message.Message,), {
  'DESCRIPTOR' : _OFFSETBACKREF,
  '__module__' : 'deflateinfo_pb2'
  # @@protoc_insertion_point(class_scope:DEFLATEProto.OffsetBackref)
  })
_sym_db.RegisterMessage(OffsetBackref)

DeflateSym = _reflection.GeneratedProtocolMessageType('DeflateSym', (_message.Message,), {
  'DESCRIPTOR' : _DEFLATESYM,
  '__module__' : 'deflateinfo_pb2'
  # @@protoc_insertion_point(class_scope:DEFLATEProto.DeflateSym)
  })
_sym_db.RegisterMessage(DeflateSym)

UncompressedBlock = _reflection.GeneratedProtocolMessageType('UncompressedBlock', (_message.Message,), {
  'DESCRIPTOR' : _UNCOMPRESSEDBLOCK,
  '__module__' : 'deflateinfo_pb2'
  # @@protoc_insertion_point(class_scope:DEFLATEProto.UncompressedBlock)
  })
_sym_db.RegisterMessage(UncompressedBlock)

CompressedBlock = _reflection.GeneratedProtocolMessageType('CompressedBlock', (_message.Message,), {

  'LenlitCodelenEntry' : _reflection.GeneratedProtocolMessageType('LenlitCodelenEntry', (_message.Message,), {
    'DESCRIPTOR' : _COMPRESSEDBLOCK_LENLITCODELENENTRY,
    '__module__' : 'deflateinfo_pb2'
    # @@protoc_insertion_point(class_scope:DEFLATEProto.CompressedBlock.LenlitCodelenEntry)
    })
  ,

  'DistCodelenEntry' : _reflection.GeneratedProtocolMessageType('DistCodelenEntry', (_message.Message,), {
    'DESCRIPTOR' : _COMPRESSEDBLOCK_DISTCODELENENTRY,
    '__module__' : 'deflateinfo_pb2'
    # @@protoc_insertion_point(class_scope:DEFLATEProto.CompressedBlock.DistCodelenEntry)
    })
  ,
  'DESCRIPTOR' : _COMPRESSEDBLOCK,
  '__module__' : 'deflateinfo_pb2'
  # @@protoc_insertion_point(class_scope:DEFLATEProto.CompressedBlock)
  })
_sym_db.RegisterMessage(CompressedBlock)
_sym_db.RegisterMessage(CompressedBlock.LenlitCodelenEntry)
_sym_db.RegisterMessage(CompressedBlock.DistCodelenEntry)

UnderlyingBlock = _reflection.GeneratedProtocolMessageType('UnderlyingBlock', (_message.Message,), {
  'DESCRIPTOR' : _UNDERLYINGBLOCK,
  '__module__' : 'deflateinfo_pb2'
  # @@protoc_insertion_point(class_scope:DEFLATEProto.UnderlyingBlock)
  })
_sym_db.RegisterMessage(UnderlyingBlock)

DEFLATEBlock = _reflection.GeneratedProtocolMessageType('DEFLATEBlock', (_message.Message,), {
  'DESCRIPTOR' : _DEFLATEBLOCK,
  '__module__' : 'deflateinfo_pb2'
  # @@protoc_insertion_point(class_scope:DEFLATEProto.DEFLATEBlock)
  })
_sym_db.RegisterMessage(DEFLATEBlock)

DEFLATEStream = _reflection.GeneratedProtocolMessageType('DEFLATEStream', (_message.Message,), {
  'DESCRIPTOR' : _DEFLATESTREAM,
  '__module__' : 'deflateinfo_pb2'
  # @@protoc_insertion_point(class_scope:DEFLATEProto.DEFLATEStream)
  })
_sym_db.RegisterMessage(DEFLATEStream)


_COMPRESSEDBLOCK_LENLITCODELENENTRY._options = None
_COMPRESSEDBLOCK_DISTCODELENENTRY._options = None
# @@protoc_insertion_point(module_scope)
