# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: lz77info.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='lz77info.proto',
  package='LZ77',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x0elz77info.proto\x12\x04LZ77\"\x18\n\x07Literal\x12\r\n\x05value\x18\x01 \x01(\r\"+\n\x07\x42\x61\x63kref\x12\x0e\n\x06length\x18\x01 \x01(\r\x12\x10\n\x08\x64istance\x18\x02 \x01(\r\"A\n\rOffsetBackref\x12\x0e\n\x06offset\x18\x01 \x01(\r\x12\x0e\n\x06length\x18\x02 \x01(\r\x12\x10\n\x08\x64istance\x18\x03 \x01(\r\"z\n\nDeflateSym\x12\x1c\n\x03lit\x18\x01 \x01(\x0b\x32\r.LZ77.LiteralH\x00\x12 \n\x07\x62\x61\x63kref\x18\x02 \x01(\x0b\x32\r.LZ77.BackrefH\x00\x12%\n\x06offset\x18\x03 \x01(\x0b\x32\x13.LZ77.OffsetBackrefH\x00\x42\x05\n\x03sym\"D\n\nCompressed\x12\x16\n\x0enbytes_decoded\x18\x01 \x01(\r\x12\x1e\n\x04syms\x18\x02 \x03(\x0b\x32\x10.LZ77.DeflateSymb\x06proto3'
)




_LITERAL = _descriptor.Descriptor(
  name='Literal',
  full_name='LZ77.Literal',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='value', full_name='LZ77.Literal.value', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=24,
  serialized_end=48,
)


_BACKREF = _descriptor.Descriptor(
  name='Backref',
  full_name='LZ77.Backref',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='length', full_name='LZ77.Backref.length', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='distance', full_name='LZ77.Backref.distance', index=1,
      number=2, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=50,
  serialized_end=93,
)


_OFFSETBACKREF = _descriptor.Descriptor(
  name='OffsetBackref',
  full_name='LZ77.OffsetBackref',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='offset', full_name='LZ77.OffsetBackref.offset', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='length', full_name='LZ77.OffsetBackref.length', index=1,
      number=2, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='distance', full_name='LZ77.OffsetBackref.distance', index=2,
      number=3, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=95,
  serialized_end=160,
)


_DEFLATESYM = _descriptor.Descriptor(
  name='DeflateSym',
  full_name='LZ77.DeflateSym',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='lit', full_name='LZ77.DeflateSym.lit', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='backref', full_name='LZ77.DeflateSym.backref', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='offset', full_name='LZ77.DeflateSym.offset', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='sym', full_name='LZ77.DeflateSym.sym',
      index=0, containing_type=None,
      create_key=_descriptor._internal_create_key,
    fields=[]),
  ],
  serialized_start=162,
  serialized_end=284,
)


_COMPRESSED = _descriptor.Descriptor(
  name='Compressed',
  full_name='LZ77.Compressed',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='nbytes_decoded', full_name='LZ77.Compressed.nbytes_decoded', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='syms', full_name='LZ77.Compressed.syms', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=286,
  serialized_end=354,
)

_DEFLATESYM.fields_by_name['lit'].message_type = _LITERAL
_DEFLATESYM.fields_by_name['backref'].message_type = _BACKREF
_DEFLATESYM.fields_by_name['offset'].message_type = _OFFSETBACKREF
_DEFLATESYM.oneofs_by_name['sym'].fields.append(
  _DEFLATESYM.fields_by_name['lit'])
_DEFLATESYM.fields_by_name['lit'].containing_oneof = _DEFLATESYM.oneofs_by_name['sym']
_DEFLATESYM.oneofs_by_name['sym'].fields.append(
  _DEFLATESYM.fields_by_name['backref'])
_DEFLATESYM.fields_by_name['backref'].containing_oneof = _DEFLATESYM.oneofs_by_name['sym']
_DEFLATESYM.oneofs_by_name['sym'].fields.append(
  _DEFLATESYM.fields_by_name['offset'])
_DEFLATESYM.fields_by_name['offset'].containing_oneof = _DEFLATESYM.oneofs_by_name['sym']
_COMPRESSED.fields_by_name['syms'].message_type = _DEFLATESYM
DESCRIPTOR.message_types_by_name['Literal'] = _LITERAL
DESCRIPTOR.message_types_by_name['Backref'] = _BACKREF
DESCRIPTOR.message_types_by_name['OffsetBackref'] = _OFFSETBACKREF
DESCRIPTOR.message_types_by_name['DeflateSym'] = _DEFLATESYM
DESCRIPTOR.message_types_by_name['Compressed'] = _COMPRESSED
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Literal = _reflection.GeneratedProtocolMessageType('Literal', (_message.Message,), {
  'DESCRIPTOR' : _LITERAL,
  '__module__' : 'lz77info_pb2'
  # @@protoc_insertion_point(class_scope:LZ77.Literal)
  })
_sym_db.RegisterMessage(Literal)

Backref = _reflection.GeneratedProtocolMessageType('Backref', (_message.Message,), {
  'DESCRIPTOR' : _BACKREF,
  '__module__' : 'lz77info_pb2'
  # @@protoc_insertion_point(class_scope:LZ77.Backref)
  })
_sym_db.RegisterMessage(Backref)

OffsetBackref = _reflection.GeneratedProtocolMessageType('OffsetBackref', (_message.Message,), {
  'DESCRIPTOR' : _OFFSETBACKREF,
  '__module__' : 'lz77info_pb2'
  # @@protoc_insertion_point(class_scope:LZ77.OffsetBackref)
  })
_sym_db.RegisterMessage(OffsetBackref)

DeflateSym = _reflection.GeneratedProtocolMessageType('DeflateSym', (_message.Message,), {
  'DESCRIPTOR' : _DEFLATESYM,
  '__module__' : 'lz77info_pb2'
  # @@protoc_insertion_point(class_scope:LZ77.DeflateSym)
  })
_sym_db.RegisterMessage(DeflateSym)

Compressed = _reflection.GeneratedProtocolMessageType('Compressed', (_message.Message,), {
  'DESCRIPTOR' : _COMPRESSED,
  '__module__' : 'lz77info_pb2'
  # @@protoc_insertion_point(class_scope:LZ77.Compressed)
  })
_sym_db.RegisterMessage(Compressed)


# @@protoc_insertion_point(module_scope)
